services:
  master:
    build:
      context: .
      dockerfile: ./dockerfiles/master.Dockerfile
    working_dir: /root/playbooks
    volumes:
      - ./volumes/ansible/playbooks:/root/playbooks
      - ./volumes/ansible/config:/etc/ansible
    command: tail -f /dev/null
    
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/server.Dockerfile

  db:
    build:
      context: .
      dockerfile: ./dockerfiles/server.Dockerfile

  lb:
    build:
      context: .
      dockerfile: ./dockerfiles/server.Dockerfile
    ports: 
    - 8080:80
